let nextId : number = 1;

function generateId():number{
    return nextId++;
}

type Speech = {
    id: number;
    title: string;
    lines: Array<string>;
};

const data: Array<Speech> = [
    {
        id: generateId(),
        title: "Message to the Grassroots",
        lines: [
            "And during the few moments that we have left, we want to have just an off-the-cuff chat between you and me — us. We want to talk right down to earth in a language that everybody here can easily understand. We all agree tonight, all of the speakers have agreed, that America has a very serious problem. Not only does America have a very serious problem, but our people have a very serious problem. America’s problem is us. We’re her problem. The only reason she has a problem is she doesn’t want us here. And every time you look at yourself, be you black, brown, red, or yellow — a so-called Negro — you represent a person who poses such a serious problem for America because you’re not wanted. Once you face this as a fact, then you can start plotting a course that will make you appear intelligent, instead of unintelligent.",
            "What you and I need to do is learn to forget our differences. When we come together, we don’t come together as Baptists or Methodists. You don’t catch hell ’cause you’re a Baptist, and you don’t catch hell ’cause you’re a Methodist. You don’t catch hell ’cause you’re a Methodist or Baptist. You don’t catch hell because you’re a Democrat or a Republican. You don’t catch hell because you’re a Mason or an Elk. And you sure don’t catch hell ’cause you’re an American; ’cause if you was an American, you wouldn’t catch no hell. You catch hell ’cause you’re a black man. You catch hell, all of us catch hell, for the same reason.",
            "So we are all black people, so-called Negroes, second-class citizens, ex-slaves. You are nothing but a ex-slave. You don’t like to be told that. But what else are you? You are ex-slaves. You didn’t come here on the “Mayflower.” You came here on a slave ship — in chains, like a horse, or a cow, or a chicken. And you were brought here by the people who came here on the “Mayflower.” You were brought here by the so-called Pilgrims, or Founding Fathers. They were the ones who brought you here.",
            "We have a common enemy. We have this in common: We have a common oppressor, a common exploiter, and a common discriminator. But once we all realize that we have this common enemy, then we unite on the basis of what we have in common. And what we have foremost in common is that enemy — the white man. He’s an enemy to all of us. I know some of you all think that some of them aren’t enemies. Time will tell.",
            "In Bandung back in, I think, 1954, was the first unity meeting in centuries of black people. And once you study what happened at the Bandung conference, and the results of the Bandung conference, it actually serves as a model for the same procedure you and I can use to get our problems solved. At Bandung all the nations came together. Their were dark nations from Africa and Asia. Some of them were Buddhists. Some of them were Muslim. Some of them were Christians. Some of them were Confucianists; some were atheists. Despite their religious differences, they came together. Some were communists; some were socialists; some were capitalists. Despite their economic and political differences, they came together. All of them were black, brown, red, or yellow. The number-one thing that was not allowed to attend the Bandung conference was the white man. He couldn’t come. Once they excluded the white man, they found that they could get together. Once they kept him out, everybody else fell right in and fell in line. This is the thing that you and I have to understand. And these people who came together didn’t have nuclear weapons; they didn’t have jet planes; they didn’t have all of the heavy armaments that the white man has. But they had unity.",
            "They were able to submerge their little petty differences and agree on one thing: That though one African came from Kenya and was being colonized by the Englishman, and another African came from the Congo and was being colonized by the Belgian, and another African came from Guinea and was being colonized by the French, and another came from Angola and was being colonized by the Portuguese. When they came to the Bandung conference, they looked at the Portuguese, and at the Frenchman, and at the Englishman, and at the other — Dutchman — and learned or realized that the one thing that all of them had in common: they were all from Europe, they were all Europeans, blond, blue-eyed and white-skinned. They began to recognize who their enemy was. The same man that was colonizing our people in Kenya was colonizing our people in the Congo. The same one in the Congo was colonizing our people in South Africa, and in Southern Rhodesia, and in Burma, and in India, and in Afghanistan, and in Pakistan. They realized all over the world where the dark man was being oppressed, he was being oppressed by the white man; where the dark man was being exploited, he was being exploited by the white man. So they got together under this basis — that they had a common enemy.",
            "And when you and I here in Detroit and in Michigan and in America who have been awakened today look around us, we too realize here in America we all have a common enemy, whether he’s in Georgia or Michigan, whether he’s in California or New York. He’s the same man: blue eyes and blond hair and pale skin — same man. So what we have to do is what they did. They agreed to stop quarreling among themselves. Any little spat that they had, they’d settle it among themselves, go into a huddle — don’t let the enemy know that you got a disagreement.",
            "Instead of us airing our differences in public, we have to realize we’re all the same family. And when you have a family squabble, you don’t get out on the sidewalk. If you do, everybody calls you uncouth, unrefined, uncivilized, savage. If you don’t make it at home, you settle it at home; you get in the closet — argue it out behind closed doors. And then when you come out on the street, you pose a common front, a united front. And this is what we need to do in the community, and in the city, and in the state. We need to stop airing our differences in front of the white man. Put the white man out of our meetings, number one, and then sit down and talk shop with each other. [That’s] all you gotta do."
        ]
    },
    {
        id: generateId(),
        title: "Speech at Ford Auditorium",
        lines: [
            "Attorney Milton Henry, distinguished guests, brothers and sisters, ladies and gentlemen, friends and enemies:",
            "I want to point out first that I am very happy to be here this evening and I’m thankful for the invitation to come here to Detroit this evening. I was in a house last night that was bombed, my own. It didn’t destroy all my clothes, not all, but you know what happens when fire dashes through–they get smoky. The only thing I could get my hands on before leaving was what I have on now.",
            "It isn’t something that made me lose confidence in what I am doing, because my wife understands and I have children from this size on down, and even in their young age they understand. I think they would rather have a father or brother or whatever the situation may be who will take a stand in the face of any kind of reaction from narrow-minded people rather than to compromise and later on have to grow up in shame and in disgrace.",
            "So I just ask you to excuse my appearance. I don’t normally come out in front of people without a shirt and a tie. I guess that’s somewhat a holdover from the ‘Black Muslim’ movement, which I was in. That’s one of the good aspects of that movement. It teaches you to be very careful and conscious of how you look, which is a positive contribution on their part. But that positive contribution on their part is greatly offset by too many other liabilities.",
            "Tonight we want to discuss–and by the way, also, when I came here today I was a bit–last night, the temperature was about twenty above and when this explosion took place, I was caught in what I had on, some pajamas. And in trying to get my family out of the house, none of us stopped for any clothes at that point–twenty-degree cold. I myself was–I had gotten them into the house of the neighbor next door. So I thought perhaps being in that condition for so long I would get pneumonia or a cold or something like that, so a doctor came today–a nice doctor too–and he shot something in my arm that naturally put me to sleep. I’ve been back there asleep ever since the program started in order to get back in shape. So if I have a tendency to stutter or slow down, it’s still the effects of that drug. I don’t know what kind it was, but it was good; it makes you sleep, and there’s nothing like sleeping through a whole lot of excitement.",
            "Tonight one of the things that has to be stressed is that which has not only the United States very much worried but which also has France, Great Britain, and most of the powers, who formerly were known as colonial powers, worried also, and that primarily is the African revolution. They are more concerned with the revolution that’s taking place on the African continent than they are with the revolution in Asia and in Latin America. And this is because there are so many people of African ancestry within the domestic confines or jurisdiction of these various governments.",
            "There are four different types of people in the Western Hemisphere, all of whom have Africa as a common heritage, common origin, and that’s the–those of our eople in Latin America, who are Black, but who are in the Spanish-speaking areas.Â  Many of them ofttimes migrate back to Spain, the only difference being Spain has such bad economic conditions until many of the people from Latin America don’t think it’s worthwhile to migrate back there. And then the British and the French had a great deal of control in the Caribbean, in the West Indies. And so now you have many people from the West Indies migrating to both London–rather both England and France. The people from the British West Indies go to London, and those from the French West Indies go to Paris. And it has put France and England since World War II in the precarious position of having a sort of a commonwealth structure that makes it easy for all of the people in the commonwealth territories to come into their country with no restrictions. So there’s an increasing number of dark-skinned people in England and also in France.",
            "When I was in Africa in May, I noticed a tendency on the part of the Afro-Americans to, what I call lollygag. Everybody else who was over there had something on the ball, something they were doing, something constructive. For instance, in Ghana, just to take Ghana as an example. There would be many refugees in Ghana from South Africa. But those who were in Ghana were organized and were serving as pressure groups, some were training for military–some were being trained in how to be soldiers, but others were involved as a pressure group or lobby group to let the people of Ghana never forget what’s happening to the brother in South Africa. Also you’d have brothers there from Angola and Mozambique. But all of the Africans who were exiles from their particular country and would be in a place like Ghana or Tanganyika, now Tanzania, they would be training. Their every move would still be designed to offset what was happening to their people back home where they had left.",
            "The only difference on the continent was the American Negro. Those who were over there weren’t even thinking about these over here. This was the basic difference. The Africans, when they escaped from their respective countries that were still colonized, they didn’t try and run away from the problem. But as soon as they got where they were going, they then began to organize into pressure groups to get governmental support at the international level against the injustices they were experiencing back home.",
            "And as I said, the American Negro, or the Afro-American, who was in these various countries, some working for this government, some working for that government, some just in business–they were just socializing, they had turned their back on the cause over here, they were partying, you know.",
            "And when I went through one country in particular, I heard a lot of their complaints and I didn’t make any move on them.",
            "But when I got to another country, I found the Afro-Americans there were making the same complaints. So we sat down and talked and we organized a branch in this particular country, a branch of the OAAU, Organization of Afro-American Unity. That one was the only one in existence at that time. Then during the summer, when I went back to Africa, I was able in each country that I visited, to get the Afro-American community together and organize them and make them aware of their responsibility to those of us who are still here in the lion’s den.",
            "They began to do this quite well, and when I got to Paris and London–there are many Afro-Americans in Paris, and many in London. And in December–no, November–we organized a group in Paris and just within a very short time they had grown into a well-organized unit. And they, in conjunction with the African community, invited me to Paris, Tuesday, to address a large gathering of Parisians and Afro-Americans and people from the Caribbean and also from Africa who were interested in our struggle in this country and the rate of progress that we have been making.",
            "But since the French government and the British government and this government here, the United States, know that I have been almost fanatically stressing the importance of the Afro-American uniting with the African and working as a coalition, especially in areas which are of mutual benefit to all of us. And the governments in these different places were frightened because they know that the Black revolution that’s taking place on the outside of their house–",
            "And I might point out right here that colonialism or imperialism, as the slave system of the West is called, is not something that’s just confined to England or France or the United States. But the interests in this country are in cahoots with the interests in France and the interests in Britain. It’s one huge complex or combine, and it creates what’s known as not the American power structure or the French power structure, but it’s an international power structure. And this international power structure is used to suppress the masses of dark-skinned people all over the world and exploit them of their natural resources.",
            "So that the era in which you and I have been living during the past ten years most specifically has witnessed the upsurge on the part of the Black man in Africa against the power structure. He wants his freedom.",
            "Now, mind you, the power structure is international, and as such, its own domestic base is in London, in Paris, in Washington, D.C., and so forth. And the outside or external phase of the revolution, which is manifest in the attitude and action of the Africans today is troublesome enough. The revolution on the outside of the house, or the outside of the structure, is troublesome enough. But now the powers that be are beginning to see that this struggle on the outside by the Black man is affecting, infecting the Black man who is on the inside of that structure. I hope you understand what I’m trying to say."
        ]
    }
]

export default data;
