let nextId : number = 1;

function generateId():number{
    return nextId++;
}

type Speech = {
    id: number;
    title: string;
    lines: Array<string>;
};

const data: Array<Speech> = [
    {
        id: generateId(),
        title: "Message to the Grassroots",
        lines: [
            "And during the few moments that we have left, we want to have just an off-the-cuff chat between you and me — us. We want to talk right down to earth in a language that everybody here can easily understand. We all agree tonight, all of the speakers have agreed, that America has a very serious problem. Not only does America have a very serious problem, but our people have a very serious problem. America’s problem is us. We’re her problem. The only reason she has a problem is she doesn’t want us here. And every time you look at yourself, be you black, brown, red, or yellow — a so-called Negro — you represent a person who poses such a serious problem for America because you’re not wanted. Once you face this as a fact, then you can start plotting a course that will make you appear intelligent, instead of unintelligent.",
            "What you and I need to do is learn to forget our differences. When we come together, we don’t come together as Baptists or Methodists. You don’t catch hell ’cause you’re a Baptist, and you don’t catch hell ’cause you’re a Methodist. You don’t catch hell ’cause you’re a Methodist or Baptist. You don’t catch hell because you’re a Democrat or a Republican. You don’t catch hell because you’re a Mason or an Elk. And you sure don’t catch hell ’cause you’re an American; ’cause if you was an American, you wouldn’t catch no hell. You catch hell ’cause you’re a black man. You catch hell, all of us catch hell, for the same reason.",
            "So we are all black people, so-called Negroes, second-class citizens, ex-slaves. You are nothing but a ex-slave. You don’t like to be told that. But what else are you? You are ex-slaves. You didn’t come here on the “Mayflower.” You came here on a slave ship — in chains, like a horse, or a cow, or a chicken. And you were brought here by the people who came here on the “Mayflower.” You were brought here by the so-called Pilgrims, or Founding Fathers. They were the ones who brought you here.",
            "We have a common enemy. We have this in common: We have a common oppressor, a common exploiter, and a common discriminator. But once we all realize that we have this common enemy, then we unite on the basis of what we have in common. And what we have foremost in common is that enemy — the white man. He’s an enemy to all of us. I know some of you all think that some of them aren’t enemies. Time will tell.",
            "In Bandung back in, I think, 1954, was the first unity meeting in centuries of black people. And once you study what happened at the Bandung conference, and the results of the Bandung conference, it actually serves as a model for the same procedure you and I can use to get our problems solved. At Bandung all the nations came together. Their were dark nations from Africa and Asia. Some of them were Buddhists. Some of them were Muslim. Some of them were Christians. Some of them were Confucianists; some were atheists. Despite their religious differences, they came together. Some were communists; some were socialists; some were capitalists. Despite their economic and political differences, they came together. All of them were black, brown, red, or yellow. The number-one thing that was not allowed to attend the Bandung conference was the white man. He couldn’t come. Once they excluded the white man, they found that they could get together. Once they kept him out, everybody else fell right in and fell in line. This is the thing that you and I have to understand. And these people who came together didn’t have nuclear weapons; they didn’t have jet planes; they didn’t have all of the heavy armaments that the white man has. But they had unity.",
            "They were able to submerge their little petty differences and agree on one thing: That though one African came from Kenya and was being colonized by the Englishman, and another African came from the Congo and was being colonized by the Belgian, and another African came from Guinea and was being colonized by the French, and another came from Angola and was being colonized by the Portuguese. When they came to the Bandung conference, they looked at the Portuguese, and at the Frenchman, and at the Englishman, and at the other — Dutchman — and learned or realized that the one thing that all of them had in common: they were all from Europe, they were all Europeans, blond, blue-eyed and white-skinned. They began to recognize who their enemy was. The same man that was colonizing our people in Kenya was colonizing our people in the Congo. The same one in the Congo was colonizing our people in South Africa, and in Southern Rhodesia, and in Burma, and in India, and in Afghanistan, and in Pakistan. They realized all over the world where the dark man was being oppressed, he was being oppressed by the white man; where the dark man was being exploited, he was being exploited by the white man. So they got together under this basis — that they had a common enemy.",
            "And when you and I here in Detroit and in Michigan and in America who have been awakened today look around us, we too realize here in America we all have a common enemy, whether he’s in Georgia or Michigan, whether he’s in California or New York. He’s the same man: blue eyes and blond hair and pale skin — same man. So what we have to do is what they did. They agreed to stop quarreling among themselves. Any little spat that they had, they’d settle it among themselves, go into a huddle — don’t let the enemy know that you got a disagreement.",
            "Instead of us airing our differences in public, we have to realize we’re all the same family. And when you have a family squabble, you don’t get out on the sidewalk. If you do, everybody calls you uncouth, unrefined, uncivilized, savage. If you don’t make it at home, you settle it at home; you get in the closet — argue it out behind closed doors. And then when you come out on the street, you pose a common front, a united front. And this is what we need to do in the community, and in the city, and in the state. We need to stop airing our differences in front of the white man. Put the white man out of our meetings, number one, and then sit down and talk shop with each other. [That’s] all you gotta do.",
            "I would like to make a few comments concerning the difference between the black revolution and the Negro revolution. There’s a difference. Are they both the same? And if they’re not, what is the difference? What is the difference between a black revolution and a Negro revolution? First, what is a revolution? Sometimes I’m inclined to believe that many of our people are using this word “revolution” loosely, without taking careful consideration [of] what this word actually means, and what its historic characteristics are. When you study the historic nature of revolutions, the motive of a revolution, the objective of a revolution, and the result of a revolution, and the methods used in a revolution, you may change words. You may devise another program. You may change your goal and you may change your mind.",
            "Look at the American Revolution in 1776. That revolution was for what? For land. Why did they want land? Independence. How was it carried out? Bloodshed. Number one, it was based on land, the basis of independence. And the only way they could get it was bloodshed. The French Revolution — what was it based on? The land-less against the landlord. What was it for? Land. How did they get it? Bloodshed. Was no love lost; was no compromise; was no negotiation. I’m telling you, you don’t know what a revolution is. ‘Cause when you find out what it is, you’ll get back in the alley; you’ll get out of the way. The Russian Revolution — what was it based on? Land. The land-less against the landlord. How did they bring it about? Bloodshed. You haven’t got a revolution that doesn’t involve bloodshed. And you’re afraid to bleed. I said, you’re afraid to bleed.",
            "[As] long as the white man sent you to Korea, you bled. He sent you to Germany, you bled. He sent you to the South Pacific to fight the Japanese, you bled. You bleed for white people. But when it comes time to seeing your own churches being bombed and little black girls be murdered, you haven’t got no blood. You bleed when the white man says bleed; you bite when the white man says bite; and you bark when the white man says bark. I hate to say this about us, but it’s true. How are you going to be nonviolent in Mississippi, as violent as you were in Korea? How can you justify being nonviolent in Mississippi and Alabama, when your churches are being bombed, and your little girls are being murdered, and at the same time you’re going to violent with Hitler, and Tojo, and somebody else that you don’t even know?",
            "If violence is wrong in America, violence is wrong abroad. If it’s wrong to be violent defending black women and black children and black babies and black men, then it’s wrong for America to draft us and make us violent abroad in defense of her. And if it is right for America to draft us, and teach us how to be violent in defense of her, then it is right for you and me to do whatever is necessary to defend our own people right here in this country.",
            "The Chinese Revolution — they wanted land. They threw the British out, along with the Uncle Tom Chinese. Yeah, they did. They set a good example. When I was in prison, I read an article — don’t be shocked when I say I was in prison. You’re still in prison. That’s what America means: prison. When I was in prison, I read an article in Life magazine showing a little Chinese girl, nine years old; her father was on his hands and knees and she was pulling the trigger ’cause he was an Uncle Tom Chinaman, When they had the revolution over there, they took a whole generation of Uncle Toms — just wiped them out. And within ten years that little girl become a full-grown woman. No more Toms in China. And today it’s one of the toughest, roughest, most feared countries on this earth — by the white man. ‘Cause there are no Uncle Toms over there.",
            "Of all our studies, history is best qualified to reward our research. And when you see that you’ve got problems, all you have to do is examine the historic method used all over the world by others who have problems similar to yours. And once you see how they got theirs straight, then you know how you can get yours straight. There’s been a revolution, a black revolution, going on in Africa. In Kenya, the Mau Mau were revolutionaries; they were the ones who made the word “Uhuru” [Kenyan word for “freedom”]. They were the ones who brought it to the fore. The Mau Mau, they were revolutionaries. They believed in scorched earth. They knocked everything aside that got in their way, and their revolution also was based on land, a desire for land. In Algeria, the northern part of Africa, a revolution took place.",
            "The Algerians were revolutionists; they wanted land. France offered to let them be integrated into France. They told France: to hell with France. They wanted some land, not some France. And they engaged in a bloody battle. So I cite these various revolutions, brothers and sisters, to show you — you don’t have a peaceful revolution. You don’t have a turn-the-other-cheek revolution. There’s no such thing as a nonviolent revolution. [The] only kind of revolution that’s nonviolent is the Negro revolution. The only revolution based on loving your enemy is the Negro revolution. The only revolution in which the goal is a desegregated lunch counter, a desegregated theater, a desegregated park, and a desegregated public toilet; you can sit down next to white folks on the toilet. That’s no revolution. Revolution is based on land. Land is the basis of all independence. Land is the basis of freedom, justice, and equality.",
            "The white man knows what a revolution is. He knows that the black revolution is world-wide in scope and in nature. The black revolution is sweeping Asia, sweeping Africa, is rearing its head in Latin America. The Cuban Revolution — that’s a revolution. They overturned the system. Revolution is in Asia. Revolution is in Africa. And the white man is screaming because he sees revolution in Latin America. How do you think he’ll react to you when you learn what a real revolution is? You don’t know what a revolution is. If you did, you wouldn’t use that word.",
            "A revolution is bloody. Revolution is hostile. Revolution knows no compromise. Revolution overturns and destroys everything that gets in its way. And you, sitting around here like a knot on the wall, saying, “I’m going to love these folks no matter how much they hate me.” No, you need a revolution. Whoever heard of a revolution where they lock arms, as Reverend Cleage was pointing out beautifully, singing “We Shall Overcome”? Just tell me. You don’t do that in a revolution. You don’t do any singing; you’re too busy swinging. It’s based on land. A revolutionary wants land so he can set up his own nation, an independent nation. These Negroes aren’t asking for no nation. They’re trying to crawl back on the plantation."
        ]
    },
    {
        id: generateId(),
        title: "Speech at Ford Auditorium",
        lines: [
            "Attorney Milton Henry, distinguished guests, brothers and sisters, ladies and gentlemen, friends and enemies:",
            "I want to point out first that I am very happy to be here this evening and I’m thankful for the invitation to come here to Detroit this evening. I was in a house last night that was bombed, my own. It didn’t destroy all my clothes, not all, but you know what happens when fire dashes through–they get smoky. The only thing I could get my hands on before leaving was what I have on now.",
            "It isn’t something that made me lose confidence in what I am doing, because my wife understands and I have children from this size on down, and even in their young age they understand. I think they would rather have a father or brother or whatever the situation may be who will take a stand in the face of any kind of reaction from narrow-minded people rather than to compromise and later on have to grow up in shame and in disgrace.",
            "So I just ask you to excuse my appearance. I don’t normally come out in front of people without a shirt and a tie. I guess that’s somewhat a holdover from the ‘Black Muslim’ movement, which I was in. That’s one of the good aspects of that movement. It teaches you to be very careful and conscious of how you look, which is a positive contribution on their part. But that positive contribution on their part is greatly offset by too many other liabilities.",
            "Tonight we want to discuss–and by the way, also, when I came here today I was a bit–last night, the temperature was about twenty above and when this explosion took place, I was caught in what I had on, some pajamas. And in trying to get my family out of the house, none of us stopped for any clothes at that point–twenty-degree cold. I myself was–I had gotten them into the house of the neighbor next door. So I thought perhaps being in that condition for so long I would get pneumonia or a cold or something like that, so a doctor came today–a nice doctor too–and he shot something in my arm that naturally put me to sleep. I’ve been back there asleep ever since the program started in order to get back in shape. So if I have a tendency to stutter or slow down, it’s still the effects of that drug. I don’t know what kind it was, but it was good; it makes you sleep, and there’s nothing like sleeping through a whole lot of excitement.",
            "Tonight one of the things that has to be stressed is that which has not only the United States very much worried but which also has France, Great Britain, and most of the powers, who formerly were known as colonial powers, worried also, and that primarily is the African revolution. They are more concerned with the revolution that’s taking place on the African continent than they are with the revolution in Asia and in Latin America. And this is because there are so many people of African ancestry within the domestic confines or jurisdiction of these various governments.",
            "There are four different types of people in the Western Hemisphere, all of whom have Africa as a common heritage, common origin, and that’s the–those of our eople in Latin America, who are Black, but who are in the Spanish-speaking areas.Â  Many of them ofttimes migrate back to Spain, the only difference being Spain has such bad economic conditions until many of the people from Latin America don’t think it’s worthwhile to migrate back there. And then the British and the French had a great deal of control in the Caribbean, in the West Indies. And so now you have many people from the West Indies migrating to both London–rather both England and France. The people from the British West Indies go to London, and those from the French West Indies go to Paris. And it has put France and England since World War II in the precarious position of having a sort of a commonwealth structure that makes it easy for all of the people in the commonwealth territories to come into their country with no restrictions. So there’s an increasing number of dark-skinned people in England and also in France.",
            "When I was in Africa in May, I noticed a tendency on the part of the Afro-Americans to, what I call lollygag. Everybody else who was over there had something on the ball, something they were doing, something constructive. For instance, in Ghana, just to take Ghana as an example. There would be many refugees in Ghana from South Africa. But those who were in Ghana were organized and were serving as pressure groups, some were training for military–some were being trained in how to be soldiers, but others were involved as a pressure group or lobby group to let the people of Ghana never forget what’s happening to the brother in South Africa. Also you’d have brothers there from Angola and Mozambique. But all of the Africans who were exiles from their particular country and would be in a place like Ghana or Tanganyika, now Tanzania, they would be training. Their every move would still be designed to offset what was happening to their people back home where they had left.",
            "The only difference on the continent was the American Negro. Those who were over there weren’t even thinking about these over here. This was the basic difference. The Africans, when they escaped from their respective countries that were still colonized, they didn’t try and run away from the problem. But as soon as they got where they were going, they then began to organize into pressure groups to get governmental support at the international level against the injustices they were experiencing back home.",
            "And as I said, the American Negro, or the Afro-American, who was in these various countries, some working for this government, some working for that government, some just in business–they were just socializing, they had turned their back on the cause over here, they were partying, you know.",
            "And when I went through one country in particular, I heard a lot of their complaints and I didn’t make any move on them.",
            "But when I got to another country, I found the Afro-Americans there were making the same complaints. So we sat down and talked and we organized a branch in this particular country, a branch of the OAAU, Organization of Afro-American Unity. That one was the only one in existence at that time. Then during the summer, when I went back to Africa, I was able in each country that I visited, to get the Afro-American community together and organize them and make them aware of their responsibility to those of us who are still here in the lion’s den.",
            "They began to do this quite well, and when I got to Paris and London–there are many Afro-Americans in Paris, and many in London. And in December–no, November–we organized a group in Paris and just within a very short time they had grown into a well-organized unit. And they, in conjunction with the African community, invited me to Paris, Tuesday, to address a large gathering of Parisians and Afro-Americans and people from the Caribbean and also from Africa who were interested in our struggle in this country and the rate of progress that we have been making.",
            "But since the French government and the British government and this government here, the United States, know that I have been almost fanatically stressing the importance of the Afro-American uniting with the African and working as a coalition, especially in areas which are of mutual benefit to all of us. And the governments in these different places were frightened because they know that the Black revolution that’s taking place on the outside of their house–",
            "And I might point out right here that colonialism or imperialism, as the slave system of the West is called, is not something that’s just confined to England or France or the United States. But the interests in this country are in cahoots with the interests in France and the interests in Britain. It’s one huge complex or combine, and it creates what’s known as not the American power structure or the French power structure, but it’s an international power structure. And this international power structure is used to suppress the masses of dark-skinned people all over the world and exploit them of their natural resources.",
            "So that the era in which you and I have been living during the past ten years most specifically has witnessed the upsurge on the part of the Black man in Africa against the power structure. He wants his freedom.",
            "Now, mind you, the power structure is international, and as such, its own domestic base is in London, in Paris, in Washington, D.C., and so forth. And the outside or external phase of the revolution, which is manifest in the attitude and action of the Africans today is troublesome enough. The revolution on the outside of the house, or the outside of the structure, is troublesome enough. But now the powers that be are beginning to see that this struggle on the outside by the Black man is affecting, infecting the Black man who is on the inside of that structure. I hope you understand what I’m trying to say."
        ]
    },
    {
        id: generateId(),
        title:"The Ballot or the Bullet",
        lines: [
            "Mr. Moderator, Brother Lomax, brothers and sisters, friends and enemies: I just can’t believe everyone in here is a friend, and I don’t want to leave anybody out. The question tonight, as I understand it, is “The Negro Revolt, and Where Do We Go From Here?” or What Next?” In my little humble way of understanding it, it points toward either the ballot or the bullet.",
            "Before we try and explain what is meant by the ballot or the bullet, I would like to clarify something concerning myself. I’m still a Muslim; my religion is still Islam. That’s my personal belief. Just as Adam Clayton Powell is a Christian minister who heads the Abyssinian Baptist Church in New York, but at the same time takes part in the political struggles to try and bring about rights to the black people in this country; and Dr. Martin Luther King is a Christian minister down in Atlanta, Georgia, who heads another organization fighting for the civil rights of black people in this country; and Reverend Galamison, I guess you’ve heard of him, is another Christian minister in New York who has been deeply involved in the school boycotts to eliminate segregated education; well, I myself am a minister, not a Christian minister, but a Muslim minister; and I believe in action on all fronts by whatever means necessary.",
            "Although I’m still a Muslim, I’m not here tonight to discuss my religion. I’m not here to try and change your religion. I’m not here to argue or discuss anything that we differ about, because it’s time for us to submerge our differences and realize that it is best for us to first see that we have the same problem, a common problem, a problem that will make you catch hell whether you’re a Baptist, or a Methodist, or a Muslim, or a nationalist. Whether you’re educated or illiterate, whether you live on the boulevard or in the alley, you’re going to catch hell just like I am. We’re all in the same boat and we all are going to catch the same hell from the same man. He just happens to be a white man. All of us have suffered here, in this country, political oppression at the hands of the white man, economic exploitation at the hands of the white man, and social degradation at the hands of the white man.",
            "Now in speaking like this, it doesn’t mean that we’re anti-white, but it does mean we’re anti-exploitation, we’re anti-degradation, we’re anti-oppression. And if the white man doesn’t want us to be anti-him, let him stop oppressing and exploiting and degrading us. Whether we are Christians or Muslims or nationalists or agnostics or atheists, we must first learn to forget our differences. If we have differences, let us differ in the closet; when we come out in front, let us not have anything to argue about until we get finished arguing with the man. If the late President Kennedy could get together with Khrushchev and exchange some wheat, we certainly have more in common with each other than Kennedy and Khrushchev had with each other.",
            "If we don’t do something real soon, I think you’ll have to agree that we’re going to be forced either to use the ballot or the bullet. It’s one or the other in 1964. It isn’t that time is running out — time has run out!",
            "1964 threatens to be the most explosive year America has ever witnessed. The most explosive year. Why? It’s also a political year. It’s the year when all of the white politicians will be back in the so-called Negro community jiving you and me for some votes. The year when all of the white political crooks will be right back in your and my community with their false promises, building up our hopes for a letdown, with their trickery and their treachery, with their false promises which they don’t intend to keep. As they nourish these dissatisfactions, it can only lead to one thing, an explosion; and now we have the type of black man on the scene in America today — I’m sorry, Brother Lomax — who just doesn’t intend to turn the other cheek any longer.",
            "Don’t let anybody tell you anything about the odds are against you. If they draft you, they send you to Korea and make you face 800 million Chinese. If you can be brave over there, you can be brave right here. These odds aren’t as great as those odds. And if you fight here, you will at least know what you’re fighting for.",
            "I’m not a politician, not even a student of politics; in fact, I’m not a student of much of anything. I’m not a Democrat. I’m not a Republican, and I don’t even consider myself an American. If you and I were Americans, there’d be no problem. Those Honkies that just got off the boat, they’re already Americans; Polacks are already Americans; the Italian refugees are already Americans. Everything that came out of Europe, every blue-eyed thing, is already an American. And as long as you and I have been over here, we aren’t Americans yet.",
            "Well, I am one who doesn’t believe in deluding myself. I’m not going to sit at your table and watch you eat, with nothing on my plate, and call myself a diner. Sitting at the table doesn’t make you a diner, unless you eat some of what’s on that plate. Being here in America doesn’t make you an American. Being born here in America doesn’t make you an American. Why, if birth made you American, you wouldn’t need any legislation; you wouldn’t need any amendments to the Constitution; you wouldn’t be faced with civil-rights filibustering in Washington, D.C., right now. They don’t have to pass civil-rights legislation to make a Polack an American.",
            "No, I’m not an American. I’m one of the 22 million black people who are the victims of Americanism. One of the 22 million black people who are the victims of democracy, nothing but disguised hypocrisy. So, I’m not standing here speaking to you as an American, or a patriot, or a flag-saluter, or a flag-waver — no, not I. I’m speaking as a victim of this American system. And I see America through the eyes of the victim. I don’t see any American dream; I see an American nightmare.",
            "These 22 million victims are waking up. Their eyes are coming open. They’re beginning to see what they used to only look at. They’re becoming politically mature. They are realizing that there are new political trends from coast to coast. As they see these new political trends, it’s possible for them to see that every time there’s an election the races are so close that they have to have a recount. They had to recount in Massachusetts to see who was going to be governor, it was so close. It was the same way in Rhode Island, in Minnesota, and in many other parts of the country. And the same with Kennedy and Nixon when they ran for president. It was so close they had to count all over again. Well, what does this mean? It means that when white people are evenly divided, and black people have a bloc of votes of their own, it is left up to them to determine who’s going to sit in the White House and who’s going to be in the dog house.",
            "lt was the black man’s vote that put the present administration in Washington, D.C. Your vote, your dumb vote, your ignorant vote, your wasted vote put in an administration in Washington, D.C., that has seen fit to pass every kind of legislation imaginable, saving you until last, then filibustering on top of that. And your and my leaders have the audacity to run around clapping their hands and talk about how much progress we’re making. And what a good president we have. If he wasn’t good in Texas, he sure can’t be good in Washington, D.C. Because Texas is a lynch state. It is in the same breath as Mississippi, no different; only they lynch you in Texas with a Texas accent and lynch you in Mississippi with a Mississippi accent. And these Negro leaders have the audacity to go and have some coffee in the White House with a Texan, a Southern cracker — that’s all he is — and then come out and tell you and me that he’s going to be better for us because, since he’s from the South, he knows how to deal with the Southerners. What kind of logic is that? Let Eastland be president, he’s from the South too. He should be better able to deal with them than Johnson.",
            "In this present administration they have in the House of Representatives 257 Democrats to only 177 Republicans. They control two-thirds of the House vote. Why can’t they pass something that will help you and me? In the Senate, there are 67 senators who are of the Democratic Party. Only 33 of them are Republicans. Why, the Democrats have got the government sewed up, and you’re the one who sewed it up for them. And what have they given you for it? Four years in office, and just now getting around to some civil-rights legislation. Just now, after everything else is gone, out of the way, they’re going to sit down now and play with you all summer long — the same old giant con game that they call filibuster. All those are in cahoots together. Don’t you ever think they’re not in cahoots together, for the man that is heading the civil-rights filibuster is a man from Georgia named Richard Russell. When Johnson became president, the first man he asked for when he got back to Washington, D.C., was “Dicky” — that’s how tight they are. That’s his boy, that’s his pal, that’s his buddy. But they’re playing that old con game. One of them makes believe he’s for you, and he’s got it fixed where the other one is so tight against you, he never has to keep his promise.",
            "So it’s time in 1964 to wake up. And when you see them coming up with that kind of conspiracy, let them know your eyes are open. And let them know you — something else that’s wide open too. It’s got to be the ballot or the bullet. The ballot or the bullet. If you’re afraid to use an expression like that, you should get on out of the country; you should get back in the cotton patch; you should get back in the alley. They get all the Negro vote, and after they get it, the Negro gets nothing in return. All they did when they got to Washington was give a few big Negroes big jobs. Those big Negroes didn’t need big jobs, they already had jobs. That’s camouflage, that’s trickery, that’s treachery, window-dressing. I’m not trying to knock out the Democrats for the Republicans. We’ll get to them in a minute. But it is true; you put the Democrats first and the Democrats put you last.",
            "Look at it the way it is. What alibis do they use, since they control Congress and the Senate? What alibi do they use when you and I ask, “Well, when are you going to keep your promise?” They blame the Dixiecrats. What is a Dixiecrat? A Democrat. A Dixiecrat is nothing but a Democrat in disguise. The titular head of the Democrats is also the head of the Dixiecrats, because the Dixiecrats are a part of the Democratic Party. The Democrats have never kicked the Dixiecrats out of the party. The Dixiecrats bolted themselves once, but the Democrats didn’t put them out. Imagine, these lowdown Southern segregationists put the Northern Democrats down. But the Northern Democrats have never put the Dixiecrats down. No, look at that thing the way it is. They have got a con game going on, a political con game, and you and I are in the middle. It’s time for you and me to wake up and start looking at it like it is, and trying to understand it like it is; and then we can deal with it like it is.",
            "The Dixiecrats in Washington, D.C., control the key committees that run the government. The only reason the Dixiecrats control these committees is because they have seniority. The only reason they have seniority is because they come from states where Negroes can’t vote. This is not even a government that’s based on democracy. lt. is not a government that is made up of representatives of the people. Half of the people in the South can’t even vote. Eastland is not even supposed to be in Washington. Half of the senators and congressmen who occupy these key positions in Washington, D.C., are there illegally, are there unconstitutionally.",
            "I was in Washington, D.C., a week ago Thursday, when they were debating whether or not they should let the bill come onto the floor. And in the back of the room where the Senate meets, there’s a huge map of the United States, and on that map it shows the location of Negroes throughout the country. And it shows that the Southern section of the country, the states that are most heavily concentrated with Negroes, are the ones that have senators and congressmen standing up filibustering and doing all other kinds of trickery to keep the Negro from being able to vote. This is pitiful. But it’s not pitiful for us any longer; it’s actually pitiful for the white man, because soon now, as the Negro awakens a little more and sees the vise that he’s in, sees the bag that he’s in, sees the real game that he’s in, then the Negro’s going to develop a new tactic."


        ]
    }
]

export { data, type Speech };
